# Generated by Django 3.2.16 on 2022-12-27 14:31

from django.db import migrations, models
import uuid


def user_uuid_forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model('accounts', 'User')
    for user in User.objects.using(db_alias).all():
        user.user_uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name'),
    ]

    operations = [

        migrations.DeleteModel(
            name='Profile',
        ),

        migrations.AddField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(user_uuid_forward),
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),

    ]
