# Generated by Django 3.2.16 on 2022-12-27 15:04
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221227_1731'),
        ('songs', '0003_auto_20221227_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
