# Generated by Django 3.2.16 on 2022-12-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221227_1804'),
    ]

    operations = [
    ]
