repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black src
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort src
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 src
        language: python
        types: [python]
