version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    restart: always
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - PROVIDER=cloudflare
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django-app
    expose:
      - "8000"
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

volumes:
  pgdata:
  static_volume:
