# Generated by Django 3.2.16 on 2022-12-27 14:56

from django.db import migrations, models
import uuid


def song_user_uuid_forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model('accounts', 'User')
    Song = apps.get_model('songs', 'Song')
    for song in Song.objects.using(db_alias).all():
        if song.user_id:
            song.user_uuid = User.objects.get(id=song.user_id).user_uuid
            song.save()


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_tagulous'),
        ('accounts', '0003_auto_20221227_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),

        migrations.RunPython(song_user_uuid_forward),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='user_uuid',
            new_name='user',
        ),
    ]
