# Generated by Django 3.2.16 on 2022-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20221227_1756'),
        ('accounts', '0004_auto_20221227_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.DO_NOTHING, to='accounts.user')
        ),
    ]
