name: Deploy on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/worship47
          git fetch --all
          git checkout ${{ github.ref_name }}
          docker compose down
          docker compose up -d --build
          docker compose exec web uv run manage.py migrate --noinput &&
          docker compose exec web uv run manage.py collectstatic --noinput &&
          echo "Deployed successfully"
        EOF
