name: Worship47 CI

on:
  push:
    branches:
      - 'master'
      - 'feature/*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install
    - name: Run Tests
      run: |
        poetry run pytest
      env:
        DEBUG: ${{ secrets.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_PORT: ${{ secrets.SQL_PORT }}
        SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
